t3: 1.0
#####################################
# カスタム機能定義
#####################################
info:
  name: rest
  customPackage: com.epion_t3.rest
  summary:
    - lang: ja_JP
      contents: REST-API関連のコマンドを提供します。
  description:
    - lang: ja_JP
      contents: REST-APIのテストをするために必要な機能を提供します。
#####################################
# コマンド定義
#####################################
commands:
  ##########################
  # ExecuteRestApi
  ##########################
  - id: ExecuteRestApi
    evidenceCommand: true
    summary:
      - lang: ja_JP
        contents: REST-APIを呼び出して結果を取得するためのコマンド。
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: REST-APIを呼び出します。対象URL「${request.targetUrl}」、メソッド「${request.method}」、
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: REST-APIを呼び出すことが可能です。
      - order: 2
        summary:
          - lang: ja_JP
            contents: レスポンスをエビデンスとして保持します。
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
          - lang: en_US
            contents: Core Functions.
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「ExecuteRestApi」固定
          - lang: en_US
            contents: Fix Value SetVariable
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
          - lang: en_US
            contents: Fix Value SetVariable
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
          - lang: en_US
            contents: Fix Value SetVariable
      - order: 5
        name: connectTimeout
        required: false
        type: string
        pattern: "[0-9]+"
        summary:
          - lang: ja_JP
            contents: "接続タイムアウトをミリ秒で指定（任意） # (1)"
        description:
          - lang: ja_JP
            contents: "REST通信の接続タイムアウトを発生させる時間をミリ秒で指定します。デフォルト値は3000ms（3s）となっています。"
      - order: 6
        name: readTimeout
        required: false
        type: string
        pattern: "[0-9]+"
        summary:
          - lang: ja_JP
            contents: "読込タイムアウトをミリ秒で指定（任意） # (2)"
        description:
          - lang: ja_JP
            contents: "REST通信の読込タイムアウトを発生させる時間をミリ秒で指定します。デフォルト値は3000ms（3s）となっています。"
      - order: 7
        name: bodyEncoding
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "リクエストボディのエンコーディング指定（任意） # (3)"
        description:
          - lang: ja_JP
            contents: "リクエストボディのエンコーディング指定を行えます。デフォルト値は存在しないため、Javaの起動時のエンコーディングが採用されます。（通常UTF-8）また、このオプションはPOST、PUT、PATCHのみに適用されます。"
      - order: 8
        name: request
        required: true
        type: object
        summary:
          - lang: ja_JP
            contents: "リクエスト詳細指定"
        property:
          - order: 1
            name: method
            required: true
            type: string
            summary:
              - lang: ja_JP
                contents: "HTTPのメソッドを指定（get、post、put、deleteのいずれかに対応）"
          - order: 2
            name: headers
            required: false
            type: map
            summary:
              - lang: ja_JP
                contents: "HTTPヘッダを表す連想配列にて必要なものを指定"
          - order: 3
            name: queryParameters
            required: false
            type: array
            summary:
              - lang: ja_JP
                contents: "HTTPのクエリーパラメータを指定する"
            property:
              - order: 1
                name: name
                required: true
                type: string
                summary:
                  - lang: ja_JP
                    contents: "HTTPのメソッドを指定（get、post、put、deleteのいずれかに対応）"
              - order: 2
                name: value
                required: true
                type: string
                summary:
                  - lang: ja_JP
                    contents: "HTTPのメソッドを指定（get、post、put、deleteのいずれかに対応）"
              - order: 3
                name: needUrlEncoded
                required: true
                type: boolean
                summary:
                  - lang: ja_JP
                    contents: "HTTPのメソッドを指定（get、post、put、deleteのいずれかに対応）"
          - order: 4
            name: targetUrl
            required: true
            type: string
            summary:
              - lang: ja_JP
                contents: "リクエスト対象URLを指定"
          - order: 5
            name: body
            required: false
            type: string
            summary:
              - lang: ja_JP
                contents: "リクエストBodyを指定"
  ##########################
  # StoreJsonElement
  ##########################
  - id: StoreJsonElement
    summary:
      - lang: ja_JP
        contents: レスポンスのボディを解析して値を抽出し、Variableへ登録するための機能です。REST-APIを連続して実行するようなシナリオにおいて、レスポンスの値を引き継ぐ必要がある場合に利用します。
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: レスポンスBodyのJSONからJSONPath表記で「${jsonPath}」から値を取得し、変数「${value}」へ設定する。
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "REST-APIの実行結果のレスポンスボディ（JSONに限る）から値を[JSONPath](https://github.com/json-path/JsonPath)で抽出して変数に登録する。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「StoreJsonElement」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: target
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "ExecuteRestApiを実行したFlowID # (1)"
        description:
          - lang: ja_JP
            contents: "ExecuteRestApiを実行したFlowIDを指定します。"
      - order: 6
        name: value
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "登録する変数名 # (2)"
        description:
          - lang: ja_JP
            contents: "登録する変数名は、スコープ.名称で指定します。（例：scenario.hoge）"
      - order: 7
        name: jsonPath
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "抽出するJSONPath # (3)"
        description:
          - lang: ja_JP
            contents: "[JSONPath](https://github.com/json-path/JsonPath)にて指定を行います。"
  ##########################
  # AssertHttpHeader
  ##########################
  - id: AssertHttpHeader
    assertCommand: true
    summary:
      - lang: ja_JP
        contents: "REST-APIの実行結果のHTTPヘッダを確認します。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "REST-APIの実行結果からHTTPヘッダ「${header}」の値が「${value}」であることを確認。"
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "REST-APIの実行結果のHTTPヘッダを確認します。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「AssertHttpHeader」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: target
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "ExecuteRestApiを実行したFlowID # (1)"
        description:
          - lang: ja_JP
            contents: "ExecuteRestApiを実行したFlowIDを指定します。"
      - order: 6
        name: value
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "期待値 # (2)"
        description:
          - lang: ja_JP
            contents: "期待値としてのHTTPヘッダの値を設定します。設定値が複数項目の場合、セミコロン区切りで指定してください。"
      - order: 7
        name: header
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "HTTPヘッダ名 # (3)"
        description:
          - lang: ja_JP
            contents: "確認対象のHTTPヘッダ名を指定します。"
  ##########################
  # AssertHttpStatus
  ##########################
  - id: AssertHttpStatus
    assertCommand: true
    summary:
      - lang: ja_JP
        contents: "REST-APIの実行結果のHTTPステータスコードを確認します。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "REST-APIの実行結果からHTTPステータスの値が「${value}」であることを確認。"
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "REST-APIの実行結果のHTTPステータスコードを確認します。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「AssertHttpStatus」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: target
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "ExecuteRestApiを実行したFlowID # (1)"
        description:
          - lang: ja_JP
            contents: "ExecuteRestApiを実行したFlowIDを指定します。"
      - order: 6
        name: value
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "期待値 # (2)"
        description:
          - lang: ja_JP
            contents: "期待値としてのHTTPステータスコードを数値で設定します。"
  ##########################
  # AssertResponseBodyJson
  ##########################
  - id: AssertResponseBodyJson
    assertCommand: true
    summary:
      - lang: ja_JP
        contents: "REST-APIの実行結果のBodyを確認します。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "TODO"
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "REST-APIの実行結果のBodyを確認します。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "期待値のJSONファイルとの比較を行います。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「AssertResponseBodyJson」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: target
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "ExecuteRestApiを実行したFlowID # (1)"
        description:
          - lang: ja_JP
            contents: "ExecuteRestApiを実行したFlowIDを指定します。"
      - order: 6
        name: value
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "期待値 # (2)"
        description:
          - lang: ja_JP
            contents: "期待値としてのHTTPステータスコードを数値で設定します。"
      - order: 7
        name: ignores
        required: false
        type: array
        summary:
          - lang: ja_JP
            contents: "確認不要リスト"
        description:
          - lang: ja_JP
            contents: "確認を行わなくともよい要素、もしくはおこなことができない要素について指定します。"
#####################################
# メッセージ定義
#####################################
messages:
  - id: com.epion_t3.rest.info.1001
    message:
      - lang: ja_JP
        contents: "HTTPステータスコードは一致します."
  - id: com.epion_t3.rest.info.1002
    message:
      - lang: ja_JP
        contents: "HTTPヘッダは一致します."
  - id: com.epion_t3.rest.err.9001
    message:
      - lang: ja_JP
        contents: "不明なメソッドです.メソッド:{0}"
  - id: com.epion_t3.rest.err.9002
    message:
      - lang: ja_JP
        contents: "HTTPステータスコードは数値で指定してください.ステータスコード:{0}"
  - id: com.epion_t3.rest.err.9003
    message:
      - lang: ja_JP
        contents: "HTTPステータスコードは一致しません."
  - id: com.epion_t3.rest.err.9004
    message:
      - lang: ja_JP
        contents: "対象（target）は必須です."
  - id: com.epion_t3.rest.err.9005
    message:
      - lang: ja_JP
        contents: "値（value）は必須です."
  - id: com.epion_t3.rest.err.9006
    message:
      - lang: ja_JP
        contents: "エビデンスが参照できません.FlowID：{0}"
  - id: com.epion_t3.rest.err.9007
    message:
      - lang: ja_JP
        contents: "エビデンスはREST-APIの実行結果のレスポンスではありません.FlowID：{0}"
  - id: com.epion_t3.rest.err.9008
    message:
      - lang: ja_JP
        contents: "エビデンスのREST-APIの実行結果のレスポンスにはBodyが存在しません.FlowID：{0}"
  - id: com.epion_t3.rest.err.9009
    message:
      - lang: ja_JP
        contents: "JSONパスが不正です.JSONPath：{0}"
  - id: com.epion_t3.rest.err.9010
    message:
      - lang: ja_JP
        contents: "JSONパスは必須です."
  - id: com.epion_t3.rest.err.9011
    message:
      - lang: ja_JP
        contents: "ストアは単一プロパティのみ可能です.ArrayやObjectは不可能です.JSONPath：{0}"
  - id: com.epion_t3.rest.err.9012
    message:
      - lang: ja_JP
        contents: "接続タイムアウトは必須です."
  - id: com.epion_t3.rest.err.9013
    message:
      - lang: ja_JP
        contents: "接続タイムアウトは数値(ms)で指定してください.接続タイムアウト：{0}"
  - id: com.epion_t3.rest.err.9014
    message:
      - lang: ja_JP
        contents: "読込タイムアウトは必須です."
  - id: com.epion_t3.rest.err.9015
    message:
      - lang: ja_JP
        contents: "読込タイムアウトは数値(ms)で指定してください.読込タイムアウト：{0}"
  - id: com.epion_t3.rest.err.9016
    message:
      - lang: ja_JP
        contents: "HTTPヘッダ名は必須です."
  - id: com.epion_t3.rest.err.9017
    message:
      - lang: ja_JP
        contents: "HTTPヘッダは一致しません."
  - id: com.epion_t3.rest.err.9018
    message:
      - lang: ja_JP
        contents: "指定されたエンコーディングはサポート対象外です.エンコーディング：{0}"
